### ISSUE TITLE
Please update this, the code is 5 years old.

### ISSUE THREAD

**Issue by viniciusferrao** [xcat2/xNBA#2] opened 2019-10-26 03:47 UTC
Hello,

I'm reading the code and I think it's nothing hidden but xBNA is basically iPXE.

Theres some changes made by @jjohnson42 and that's it. So there's a way to rebase it from iPXE?

For instance, VirtIO is completely broken with modern hypervisors and the solution was simply removing the feature or issuing wontfixes:

Downgrading just because the driver isn't updated:
https://github.com/xcat2/xcat-core/pull/6412

Wontfix that can be solved if this driver is updated:
https://github.com/xcat2/xcat-core/issues/2743

The virtio.c file is 7 years old here. On upstream it's only 1 year old.

Thanks.

**Comment by jjohnson42** [comment] 2019-10-26 12:13
Long story short, I think that can be done safely now, or even switch to generic ipxe since our needs and fixes have been merged.

The only changes I did that ultimately did not merge one way or another was disabling some things that consumed neighbor table space because that was causing boot failures.  I believe that the neighbor table behavior has been improved to not need the help.  I did also add hyphenated mac support and that was merged, but with a different syntax and xnba and the plugin were ultimately changed to use the syntax that ipxe accepted.  The other change is if course changing vendor identifier because we kept attempting to use built-in ipxes that had done things like disable http instead of chaining http capable.  Ipxe now has a way of detecting features so that would be a good thing to do to switch to using plain old ipxe.

The main visible difference is that modern ipxe will be slower to boot at least under uefi with the features we build in (initializing the rng takes a while).  The last time we attempted to refresh, some system bios/uefi produced hangs or boot failures.  Particularly legacy boot was impacted, but uefi bit with elilo also has issues.

For legacy boot I'm inclined to care less nowadays.  For elilo boot, the Lenovo xCAT already disable elilo for sles 12 and rhel7 and higher, and that gets rid of those problems.  I'm inclined not to worry much about rhel6 deployment in this day and age with newer xnba/ipxe unless someone tells me otherwise.  Note it doesn't check the version of the kennel, it checks the kernel binary for the magic signature that makes it uefi ipxe compatible without an intermediate boot loader.

________________________________

**Comment by dhilst** [comment] 2019-10-28 23:46
I had bad times before trying switch from virtio to another nic driver, it was a 4 days nightmare until I try the nic driver, I can't even remember why I try it

**Comment by viniciusferrao** [comment] 2019-10-29 03:31
@jjohnson42 what is your idea here? Keep XBNA as a legacy component and have a separate and completely synced version with iPXE? So when deploying nodes with xCAT we select on the node definition which boot agent we would use with `netboot=xnba` or `netboot=ipxe`? Or just update this component and keep it as XBNA?

**Comment by jjohnson42** [comment] 2019-10-29 11:44
I'd probably update xnba.pm to accept either ipxe or xnba.  Then you could use a new packaged ipxe.  The xnba package would still be available if folks encountered an issue and needed to roll back and report the failure to the list.

The main build would probably disable https (no one uses it, it slows down boot, and I'll probably leave toward uefi http boot since that can do https and also easier to make secureboot compatible than using ipxe to provide http).
________________________________

**Comment by viniciusferrao** [comment] 2019-10-29 16:15
Thanks again @jjohnson42. Let me ask one last question. With this code updated from iPXE, this will eventually lead to aarch64 support, at least for compute nodes, right? Because if I do understood correctly your patch from: https://github.com/xcat2/xcat-core/issues/2946 needs an updated iPXE package. Right?

With this in mind, I know that I'm not your boss and you're being extremely welcoming here and on the mailing list, really thanks for this! But do you have any time schedule to deliver the updated code here? For us it will be awesome, since our lab will work better with the updated VirtIO driver, and we can test the aarch64 deployment on the machine that I've spoken on the referred ticket.

TYVM.

**Comment by jjohnson42** [comment] 2019-10-29 17:20
So there's the commit I did earlier for aarch64, which just punted on http and just tftp with grub for that moment.  I have compile ipxe for aarch64, but nothing of that effort landed anywhere and I don't even have anything where I attempted.


For the virtio driver, are you using iPXE .rom or chainbooting?  For the ipxe rom to work without having xCAT attempt a chain,, you could quickly change dhcp.pm:


-                            $lstatements = 'if option user-class-identifier = \"xNBA\" and option client-architecture = 00:00 { always-broadcast on; filename = \"http://' . $nxtsrv . $httpport  . '/tftpboot/xcat/xnba/nodes/' . $node . '\"; } else if option client-architecture = 00:07 or option client-architecture = 00:09 { filename = \"\"; option vendor-class-identifier \"PXEClient\"; } else if option client-architecture = 00:00 { filename = \"xcat/xnba.kpxe\"; } else { filename = \"\"; }' . $lstatements; #Only PXE compliant clients should ever receive xNBA
+                            $lstatements = 'if option user-class-identifier = \"iPXE\" and option client-architecture = 00:00 { always-broadcast on; filename = \"http://' . $nxtsrv . $httpport  . '/tftpboot/xcat/xnba/nodes/' . $node . '\"; } else if option client-architecture = 00:07 or option client-architecture = 00:09 { filename = \"\"; option vendor-class-identifier \"PXEClient\"; } else if option client-architecture = 00:00 { filename = \"xcat/xnba.kpxe\"; } else { filename = \"\"; }' . $lstatements; #Only PXE compliant clients should ever receive iPXE


-                        $lstatements = 'if option user-class-identifier = \"xNBA\" and option client-architecture = 00:00 { always-broadcast on; filename = \"http://' . $nxtsrv . $httpport . '/tftpboot/xcat/xnba/nodes/' . $node . '\"; } else if option user-class-identifier = \"xNBA\" and (option client-architecture = 00:09 or option client-architecture = 00:07) { filename = \"http://' . $nxtsrv . $httpport . '/tftpboot/xcat/xnba/nodes/' . $node . '.uefi\"; } else if option client-architecture = 00:07 { filename = \"xcat/xnba.efi\"; } else if option client-architecture = 00:00 { filename = \"xcat/xnba.kpxe\"; } else { filename = \"\"; }' . $lstatements; #Only PXE compliant clients should ever receive xNBA
+                        $lstatements = 'if option user-class-identifier = \"iPXE\" and option client-architecture = 00:00 { always-broadcast on; filename = \"http://' . $nxtsrv . $httpport . '/tftpboot/xcat/xnba/nodes/' . $node . '\"; } else if option user-class-identifier = \"iPXE\" and (option client-architecture = 00:09 or option client-architecture = 00:07) { filename = \"http://' . $nxtsrv . $httpport . '/tftpboot/xcat/xnba/nodes/' . $node . '.uefi\"; } else if option client-architecture = 00:07 { filename = \"xcat/xnba.efi\"; } else if option client-architecture = 00:00 { filename = \"xcat/xnba.kpxe\"; } else { filename = \"\"; }' . $lstatements; #Only PXE compliant clients should ever receive iPXE
                     } else {

-                        $lstatements = 'if option user-class-identifier = \"xNBA\" and option client-architecture = 00:00 { filename = \"http://' . $nxtsrv . $httpport . '/tftpboot/xcat/xnba/nodes/' . $node . '\"; } else if option client-architecture = 00:00 { filename = \"xcat/xnba.kpxe\"; } else { filename = \"\"; }' . $lstatements; #Only PXE compliant clients should ever receive xNBA
+                        $lstatements = 'if option user-class-identifier = \"iPXE\" and option client-architecture = 00:00 { filename = \"http://' . $nxtsrv . $httpport . '/tftpboot/xcat/xnba/nodes/' . $node . '\"; } else if option client-architecture = 00:00 { filename = \"xcat/xnba.kpxe\"; } else { filename = \"\"; }' . $lstatements; #Only PXE compliant clients should ever receive iPXE


         # $lstatements = 'if exists gpxe.bus-id { filename = \"\"; } else if exists client-architecture { filename = \"xcat/xnba.kpxe\"; } '.$lstatements;
-        push @netent, "    if option user-class-identifier = \"xNBA\" and option client-architecture = 00:00 { #x86, xCAT Network Boot Agent\n";
+        push @netent, "    if option user-class-identifier = \"iPXE\" and option client-architecture = 00:00 { #x86, xCAT Network Boot Agent\n";
         push @netent, "        always-broadcast on;\n";
         push @netent, "        filename = \"http://$tftp$httpport/tftpboot/xcat/xnba/nets/" . $net . "_" . $maskbits . "\";\n";
-        push @netent, "    } else if option user-class-identifier = \"xNBA\" and option client-architecture = 00:09 { #x86, xCAT Network Boot Agent\n";
+        push @netent, "    } else if option user-class-identifier = \"iPXE\" and option client-architecture = 00:09 { #x86, xCAT Network Boot Agent\n";
         push @netent, "        filename = \"http://$tftp$httpport/tftpboot/xcat/xnba/nets/" . $net . "_" . $maskbits . ".uefi\";\n";
-        push @netent, "    } else if option user-class-identifier = \"xNBA\" and option client-architecture = 00:07 { #x86, xCAT Network Boot Agent\n";
+        push @netent, "    } else if option user-class-identifier = \"iPXE\" and option client-architecture = 00:07 { #x86, xCAT Network Boot Agent\n";

That would just let any old build of iPXE be treated fine, so the stock ipxe that would come with the OS should work...



________________________________

**Comment by jose-d** [comment] 2019-12-07 14:51
> That would just let any old build of iPXE be treated fine, so the stock ipxe that would come with the OS should work...

hi, I'm not sure if kernel argument: `BOOTIF=01-${netX/machyp}` generated by xCat is compatible with stock iPXE boot process.
For me it was failing there and as I have no so deep knowledge in this, i did workaround by using the hashsign at the end of `addkcmdline` - effectively commenting-out everything behind..:

Also to specify initrd filename was needed to boot with ipxe..

```
addkcmdline=initrd=initrd.img raid=noautodetect #
```

I suspect the `netX/machyp` is coming from here - `xCAT_plugin/xnba.pm`:

```
301                 if ($kern->{kcmdline}) {
302                     print $pcfg "imgargs kernel " . $kern->{kcmdline} . ' BOOTIF=01-${netX/machyp}' . "\n";
303                 } else {
304                     print $pcfg "imgargs kernel BOOTIF=" . '${netX/mac}' . "\n";
305                 }
```

**Comment by viniciusferrao** [comment] 2020-05-25 18:30
It appears that @ajw1980 fixed this issue here: https://github.com/xcat2/xcat-core/issues/6567

**Comment by Hoeze** [comment] 2020-08-28 15:22
Does this mean, one can directly use iPXE insead of xnba in xcat?
How would one do this?

**Comment by jjohnson42** [comment] 2020-08-28 15:40
If /tftpboot/xcat/xnba.kpxe and xnba.efi were ipxe generic builds, then replacing 'xNBA' with 'iPXE' in dhcp.pm should in theory suffice.

As mentioned earlier, the initial reasons driving the differently labeled build are no longer applicable. There was a longstanding iPXE bug that did cause us to abort rebasing to newer code a couple of times but that was finally fixed in https://github.com/ipxe/ipxe/commit/1832f8a9b02d00977ca1e079bd9e0369763df14c

The confluent os deploy will include a build of iPXE (at least as new as the aforementioned commit), but there will be no particular idenntifier to preclude generic iPXE should we become stale).

I don't have the resources to ensure that xCAT should either rebase or abandon the 'xNBA' identifier entirely without issue, but I think it's a reasonable goal to pursue.

**Comment by ajw1980** [comment] 2020-08-28 18:49
> Does this mean, one can directly use iPXE insead of xnba in xcat?
> How would one do this?

I am using generic ipxe for both uefi and undionly booting.

If you make the changes in xcat2/xcat-core#6567, you can build the boot images with this:
```
make bin/undionly.kpxe
make bin-x86_64-efi/ipxe.efi
```

Then copy those to /tftpboot/xcat/xnba.kpxe and xnba.efi.

No changes to the xcat source were required.

**Comment by viniciusferrao** [comment] 2020-08-28 19:24
@Hoeze I can't understand either. I vote for keeping things simple, but in this case we have broken software running and this change is needed. I'm really hoping that the xCAT team will ditch xBNA in favor of upstream iPXE. I don't like to change things by myself to lose the compatibility with the upstream.

If we have an answer from the xCAT devs would be great to manage our expectations.

**Comment by ajw1980** [comment] 2020-09-21 17:37
I ran into problems pxe booting centos 8 with UEFI. I made some modifications to directly boot the kernel without the elilo chain boot which seem to be the cause of the problems. Now I see the lenovo branch already has modifications to do the same thing. @jjohnson42, can you merge the lenovo changes to the main branch? I tried both a dell and HP server and neither one of them would boot centos 8.2 with pxe chained through elilo.

**Comment by Hoeze** [comment] 2020-10-21 18:32
I finally realized that all my booting issues with Centos 8 exactly stem from this issue, that xnba alias iPXE 1.0.3 is hopelessly deprecated:
https://github.com/xcat2/xcat-core/issues/6817#issuecomment-713778934

**Comment by viniciusferrao** [comment] 2020-10-22 20:11
@cxhong sorry to mention you directly, but you seem to be the one with the powers within xCAT. This issue is starting to be counterproductive for the xCAT community. People are losing a lot of time debugging issues with xCAT when it always fallback to here. As stated on this thread, even xCAT developers lost time due to this old and deprecated code that can be fixed with a merge from the upstream or just change to iPXE directly and consume whatever the upstream creates.

There are two cited bugs that are closed with bad workarounds, the fixes and tests are already done by the community, so it appears to be just a matter of incorporating the changes.

I'm just asking to consider it.

Thank you!

**Comment by cxhong** [comment] 2020-10-22 20:55
Thanks,  @viniciusferrao 

We lost expertise in this area and also didn't have correct system to debug/verify/test this piece of code.    For the 2.16.1 release,  we merged two pull request hopefully will help the `xnba` boot issue. https://github.com/xcat2/xcat-core/pull/6772  and built new elilo package https://github.com/xcat2/xcat-core/issues/6742

We are welcome community contribute the fixes.  Specially for x86_64.  

I will review  @Hoeze  solutions for issue https://github.com/xcat2/xcat-core/issues/6817 and make necessary updates.

**Comment by jjohnson42** [comment] 2020-10-23 13:06
I'm not able to deliver thorough testing, but here is a source rpm:
https://hpc.lenovo.com/xnba/xnba-undi-20.10.23-1.src.rpm
and the resultant binary rpm:
https://hpc.lenovo.com/xnba/xnba-undi-20.10.23-1.noarch.rpm

From building a current ipxe. The procedure to make an ipxe tar.xz is simply git clone of their tree and:
tar Jcvf ipxe-10-23-2020.tar.xz --exclude-vcs ipxe

The src.rpm has one patch to rename the DHCP identifier for compatibility with xnba.pm expectations. My theory is that our previous workarounds for ipxe bugs are no longer required, however I do not have a massive system to validate that theory.

I may remove it from those urls if superseded by it being built elsewhere.

I have also had some people modify their dhcp.pm to use 'iPXE' rather than 'xNBA' to use normal iPXE, and they had good luck with that as well.

**Comment by viniciusferrao** [comment] 2020-10-27 23:56
@jjohnson42 your XNBA package is a drop in replacement?

**Comment by cxhong** [comment] 2020-10-28 16:27
I tried @jjohnson42  xNBA package and system is keeping loop at 
```
iPXE 1.0.0+ -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP HTTPS iSCSI TFTP AoE EFI Menu

net0: 6c:ae:8b:1b:e9:ba using NII on NII-0000:06:00.0 (open)
  [Link:down, TX:0 TXE:0 RX:0 RXE:0]
  [Link status: Unknown (http://ipxe.org/1a086194)]
Configuring (net0 6c:ae:8b:1b:e9:ba)...... ok
net0: 10.4.16.1/255.0.0.0 gw 10.0.0.102
net0: fe80::6eae:8bff:fe1b:e9ba/64
Next server: 10.4.40.1
Filename: xcat/xnba.efi
tftp://10.4.40.1/xcat/xnba.efi... ok
xnba.efi : 242208 bytes [EFI]
iPXE initialising devices...ok
````

**Comment by cxhong** [comment] 2020-10-28 16:45
Thanks, @Hoeze 

I built `xnba.efi` per your instruction https://github.com/Hoeze/ipxe,  looks good so far. I will do more testing.

**Comment by cxhong** [comment] 2020-11-02 20:01
@viniciusferrao, @Hoeze , @jose-d or @ajw1980     I built `xnba.efi` and `xnba.kpxe` , and can be downloaded at https://www.xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xNBA/  .  I don't have newer x86_64 system, do u have system and able to verify?
Just download those two file from `xcat.org` and replace the files in the `/tftpboot/xcat/` on the xCAT MN,  then provision a compute node.    

Thanks.

**Comment by viniciusferrao** [comment] 2020-11-02 22:12
@cxhong the link in returning "403 Forbidden" on both files, can you look at the permissions?

**Comment by besawn** [comment] 2020-11-02 22:35
@viniciusferrao I believe the permissions are corrected now, can you try again?

**Comment by viniciusferrao** [comment] 2020-11-02 22:46
@cxhong and @besawn THANK YOU SO MUCH!

It worked in both legacy and UEFI modes. Before the patch the compute nodes simples doesn't boot, hanging on the image below:

<img width="726" alt="Screen Shot 2020-11-02 at 19 10 18" src="https://user-images.githubusercontent.com/2031761/97927545-f2e46200-1d43-11eb-899c-8fa512926e71.png">

Yes! Yes! It's working perfectly now!

I cannot express how grateful I'm. How this will reach the stable branch? How can we further help?

**Comment by besawn** [comment] 2020-11-02 23:08
@viniciusferrao Thank you for testing this patch so quickly. I'm glad the patch worked for your environment. We would like to get some feedback from other members of the xCAT community to confirm that the patch appears to work as expected in a variety of x86 environments. Once we have some confidence that everything is working well, we will plan to include this in a future release. The xCAT core team has extremely limited x86 test hardware, so we appreciate any support the community can provide in this area.

**Comment by ajw1980** [comment] 2020-11-05 14:01
I've switched to these pxe images yesterday. I have a set of machines I reinstall daily which include HP, Dell, KVM, and VMware machines. The physical machines boot with uefi and the virtual machines use legacy bios mode. I install and stateless boot both Centos 8 and Fedora. All of them booted or installed correctly the last 2 days. I've been using my custom build of ipxe with that patch for several months as well.

**Comment by besawn** [comment] 2020-11-05 14:16
@ajw1980 Thank you for testing this patch and providing feedback.

**Comment by viniciusferrao** [comment] 2020-11-05 17:41
As for additional feedback, we have a customer running, up until yesterday, with `netboot=pxe` and legacy mode, since `netboot=pxe` only supports legacy mode. Changed the files, changed all 14th Gen PowerEdge R640 compute nodes with Broadcom 57412 Dual Port 10GbE SFP+ & 5720 Dual Port 1GbE BASE-T to `netboot=xnba` and boom. It worked. UEFI mode and Legacy.

**Comment by viniciusferrao** [comment] 2021-01-28 23:44
Hi @besawn and @cxhong can this be pushed to the release version of xCAT? We've been running with this patch in more than 30 clusters now, and everything is working fine.

And to be honest this patch is now mandatory, since a lot of new UEFI machines just can't boot with the shipped xNBA package.

Thank you all.

**Comment by besawn** [comment] 2021-02-03 20:45
@viniciusferrao We will be releasing this change with xCAT 2.16.2, which is the next release.

**Closed as completed** 2021-05-25 19:39 UTC
Labels: enhancement
